### PR TITLE
Feature: Local & Remote filters

### PR DESCRIPTION
**Pull request by alacasta**
# What? 

This contribution fixex #59 

The contribution includes
- A new checkbox to enable the filtering remotely or in the client side
- The modification of the non-matching logging to `light-gray` 
- A refactor of #58 

# Result

In case of having the remote filter enabled, the filter is made in remote

image

If in turn, thhe `remote filter` is disabled, the filter is made locally and the non-matching lines are displayed in gray

image

### CODE REVIEW

**Comment by alacasta** [comment]
Hi @pentix 

Please, consider reviewing this! but please, take into account that it would be better if we could first merge #58 and then this (to keep the changes better traced)

**Comment by alacasta** [comment]
I needed to change from 

```cpp
        format.setForeground(QBrush(QColorConstants::LightGray));
```

to 

```cpp
        format.setForeground(QBrush(QColor("LightGray")));
```

bc the first option didn't compile on Linux (wtf!?)

**Comment by alacasta** [comment]
@pentix

What change did u make in Travis? I am getting this when building

```
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o showbootlog.o src/showbootlog.cpp
src/showbootlog.cpp:35:10: fatal error: QRandomGenerator: No such file or directory
 #include <QRandomGenerator>
```

and yesterday at https://travis-ci.org/github/pentix/qjournalctl/builds/671358169?utm_source=github_status&utm_medium=notification it worked

```
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o showbootlog.o src/showbootlog.cpp
```

**Comment by alacasta** [comment]
> @pentix
> 
> What change did u make in Travis? I am getting this when building
> 
> ```
> g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o showbootlog.o src/showbootlog.cpp
> src/showbootlog.cpp:35:10: fatal error: QRandomGenerator: No such file or directory
>  #include <QRandomGenerator>
> ```
> 
> and yesterday at https://travis-ci.org/github/pentix/qjournalctl/builds/671358169?utm_source=github_status&utm_medium=notification it worked
> 
> ```
> g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o showbootlog.o src/showbootlog.cpp
> ```

I see no changes.... do you have any idea? `QRandomGenerator` was introduced at `Qt 5.10`...

**Comment by alacasta** [comment]
Reopening to enforce a newer CI cycle

**Comment by alacasta** [comment]
Hello @pentix,

Have you discarded adding these features? If the problem is about the CI, my plan is to shift to std rand to avoid increasing Qt version.

**Comment by pentix** [comment]
Hi Asier

No, sorry, I did not want to discard this. I deleted and pushed the old "windows-build" branch, which this PR was based upon,
and GitHub automatically closed the PR; That was not my intention...

I'm quite short on time right now, I'll look over all those PRs and try to find a simple solution so we can make it work.

Quite a while ago I started developing some features which kind of interfere with the filtering, so ideally I'd combine
your work and mine all together, but I'll check this as soon as I find time to work on my projects again. Thank you!

Btw.: GitHub does not let me reopen this, but since it's mentionend in #66, I won't forget it :)

**Pull request closed without merging**
