### PR TITLE
Small adjustment to autogen.sh and documentation for macOS compilation

### PR DESCRIPTION
**Pull request by Marcool04**
Hi there,
Having attempted successfully to adapt the `autogen.sh` script to macOS, I thought I'd try and provide a working pull request that would allow anybody to do the same.
I understand of course if you'd rather not include this, for example if you can't test it yourself and prefer to publish only tested material.
Thanks for a really handy little program!
Regards,
Mark.

### CODE REVIEW

**Comment by pentix** [comment]
Hi Mark

Thank you very much for providing this pull request!
I'm very happy it seems so handy for you that you decided to update the build system to make it available on macOS!

I will absolutely include this :) Another PR (#41) recently ported it to Windows, and there were some changes on both, the build system as well as continuous integration, so I'll likely integrate both at the same time, as soon as I find some time.

_(For my reference, here's some stuff that I want me to remember:)_

- [ ] #41 hasn't made its way to `master` yet, building the project works fine on all 3 platforms after merging
- [ ] Try to update Travis CI to build it on macOS too, maybe including artifact uploads?

Thanks again, and happy journaling! :)

**Comment by Marcool04** [comment]
No problem. Clearly quite a bit more work went into the Windows PR than this one 😉. Glad you're pleased with it. Thanks again for your work.
Regards,
Mark.

**Comment by pentix** [comment]
Merry Christmas and thanks again @Marcool04, the instructions should be complete now! :)

**Comment by Marcool04** [comment]
Hey thanks, a very merry Christmas to you too! All the best,
Mark.

**Pull request merged**
